# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

cache: packages

bioc_packages:
- BiocStyle
- biomaRt
- ComplexHeatmap
- limma
- MSstats
- org.Ag.eg.db
- org.At.tair.db
- org.Bt.eg.db
- org.Ce.eg.db
- org.Cf.eg.db
- org.Dm.eg.db
- org.Dr.eg.db
- org.EcK12.eg.db
- org.EcSakai.eg.db
- org.Gg.eg.db
- org.Hs.eg.db
- org.Mm.eg.db
- org.Mmu.eg.db
- org.Pf.plasmo.db
- org.Pt.eg.db
- org.Rn.eg.db
- org.Ss.eg.db
- org.Xl.eg.db

addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - covr
  - devtools

r_github_packages:
  - biodavidjm/artMS

r_check_args: --no-build-vignettes --no-vignettes

warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr); codecov()'
