files:
  evidence: evidence.txt
  keys: keys.txt
  contrasts: contrast.txt
  summary: summary.txt # Optional
  output: results_folder_name/results.txt # The folder must exist
qc:
  basic: 1 # 1 = yes; 0 = no
  extended: 1 # 1 = yes; 0 = no
  extendedSummary: 0 # 1 = yes; 0 = no; Requires the summary file
data:
  enabled: 1 # 1 = yes; 0 = no
  silac: 
    enabled: 0 # 1 for SILAC experiments
  filters: 
    enabled: 1
    contaminants: 1
    protein_groups: remove #remove, keep
    modifications: AB # PH, UB, AB, APMS
  sample_plots: 1 # correlation plots
msstats: # check ?MSstats::dataProcess() to find out more
  enabled: 1 # 1: activate this msstats section. 0: deactivate
  msstats_input:  # provide a msstats file if available ("-mss.txt"), otherwise, leave it blank
  profilePlots: none # Options: before, after, before-after (recommended, but time consuming), none
  normalization_method: equalizeMedians # options: equalizeMedians, quantile, 0 (no normalization), globalStandards (if chosen, include a reference protein(s)), 
  normalization_reference:  # if globalStandards is chosen, then an UNIPROT ID must be provided (or several uniprot ids, comma separated)
  summaryMethod: TMP # "TMP"(default) means Tukey's median polish, which is robust estimation method. "linear" uses linear mixed model. "logOfSum" conducts log2 (sum of intensities) per run.
  MBimpute: 1 
  censoredInt: NA
  feature_subset: all 
  n_top_feature: 3 
  logTrans: 2 
  remove_uninformative_feature_outlier: FALSE 
  min_feature_count: 2
  equalFeatureVar: TRUE
  remove50missing: FALSE
  fix_missing: 
  maxQuantileforCensored: 0.999
  use_log_file: TRUE
  append: FALSE
  log_file_path: 
output_extras:
  enabled: 1 # if 0, it wont do anything in this section
  annotate:  
    enabled: 1 # 1|0 whether to annotate the proteins in the results or not
    species: HUMAN  # Supported species: HUMAN, MOUSE, ANOPHELES, ARABIDOPSIS, BOVINE, WORM, CANINE, FLY, ZEBRAFISH, ECOLI_STRAIN_K12, ECOLI_STRAIN_SAKAI, CHICKEN, RHESUS, MALARIA, CHIMP, RAT, YEAST, PIG, XENOPUS
  plots:
    volcano: 1
    heatmap: 1
    LFC: -0.58 0.58 # Range of minimal log2fc. Default log2fc: 0.58 (a fold change of 1.5)
    FDR: 0.05 # adjusted p-value, false discovery rate
    heatmap_cluster_cols: 0
    heatmap_display: log2FC # log2FC or pvalue
